apiVersion: firestartr.dev/v1
kind: FirestartrTerraformWorkspace
metadata:
  annotations:
    firestartr.dev/claim-ref: TFWorkspaceClaim/dummy
    firestartr.dev/external-name: dummy
    firestartr.dev/policy: full-control
    firestartr.dev/last-state-pr: |
      firestartr-test/state-infra#211
    firestartr.dev/last-claim-pr: |
      firestartr-test/state-infra#211
  labels:
    claim-ref: dummy
  name: dummy-6ab3c9d3-83d4-4856-b0be-4b2c36139a70
spec:
  context:
    backend:
      ref:
        kind: FirestartrProviderConfig
        name: kubernetes-backend
    providers: []
  firestartr:
    tfStateKey: 6ab3c9d3-83d4-4856-b0be-4b2c36139a70
  source: Inline
  module: |
    output "dummy" {
      value = var.a
    }
    variable "a" {
      type = string
    }
  values: '{"a":"${{ secret_references.mi-secreto-generado.password }}"}'
  references:
    - name: rds_conn.mi-secreto-generado
      ref:
        kind: ExternalSecret
        name: mi-secreto-generado
        key: password


